{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6bc2a8e8-6b39-425e-a120-d68403a03543",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Socket bound to port 12345\n",
      "Socket is listening\n",
      "Connected to: 127.0.0.1 : 54714\n",
      "Sending message: Hello, I'm Oracle, your weather and bike hire prediction assistant. To provide accurate predictions, I need to know today's date. Please enter the date in YYYY-MM-DD format.\n",
      "Received message: 2023-08-32\n",
      "Sending message: The date format is incorrect. Please enter the date in YYYY-MM-DD format.\n",
      "Received message: 2023-08-22\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\940167\\SNS Final\\Oracle_ML_Model.py:26: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  dataset1_filtered.drop(columns=['name', 'severerisk', 'windgust',\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Sending message: Thank you. I have set the date to 2023-08-22. You can now ask me about the weather or bike hire numbers for the next 7 days. For example, 'What's the weather like on day 3?' or 'Predict bike hires for day 5.'\n",
      "Received message: how is the weather forecast on day 6?\n",
      "1/1 [==============================] - 3s 3s/step\n",
      "1/1 [==============================] - 0s 94ms/step\n",
      "1/1 [==============================] - 0s 94ms/step\n",
      "1/1 [==============================] - 0s 95ms/step\n",
      "Sending message: For Day 6, the forecast is: high of 6.4°C, low of 5.5°C, wind speed at -0.5 km/h, and precipitation levels around -1.7 mm.\n",
      "Received message: what is the estimation for number of bike hires on day 7?\n",
      "1/1 [==============================] - 2s 2s/step\n",
      "Sending message: For Day 7, the expected number of bike hires is approximately 1447.\n",
      "Received message: goodbye\n",
      "Sending message: Thank you for consulting the Oracle. Have a great day!\n",
      "Connected to: 127.0.0.1 : 54717\n",
      "Sending message: Hello, I'm Oracle, your weather and bike hire prediction assistant. To provide accurate predictions, I need to know today's date. Please enter the date in YYYY-MM-DD format.\n",
      "Received message: 2024-01-02\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\940167\\SNS Final\\Oracle_ML_Model.py:26: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  dataset1_filtered.drop(columns=['name', 'severerisk', 'windgust',\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Sending message: Thank you. I have set the date to 2024-01-02. You can now ask me about the weather or bike hire numbers for the next 7 days. For example, 'What's the weather like on day 3?' or 'Predict bike hires for day 5.'\n",
      "Received message: what is the weather like on day 3?\n",
      "1/1 [==============================] - 2s 2s/step\n",
      "1/1 [==============================] - 0s 118ms/step\n",
      "1/1 [==============================] - 0s 117ms/step\n",
      "1/1 [==============================] - 0s 98ms/step\n",
      "Sending message: For Day 3, the forecast is: high of -5.0°C, low of -1.9°C, wind speed at 6.2 km/h, and precipitation levels around -1.1 mm.\n",
      "Received message: how about the number of bike hires on day 3?\n",
      "1/1 [==============================] - 0s 128ms/step\n",
      "Sending message: For Day 3, the expected number of bike hires is approximately -8285.\n",
      "Received message: thank you\n",
      "Sending message: I'm sorry, I didn't understand. Ask about weather or bike hires.\n",
      "Received message: goodbye\n",
      "Sending message: Thank you for consulting the Oracle. Have a great day!\n"
     ]
    }
   ],
   "source": [
    "import threading\n",
    "import time\n",
    "import socket\n",
    "from _thread import *\n",
    "from Oracle_ML_Model import MyModel\n",
    "import pandas as pd\n",
    "import re\n",
    "\n",
    "print_lock = threading.Lock()\n",
    "\n",
    "class OracleBotThread(threading.Thread):\n",
    "    def __init__(self, client_socket, client_address):\n",
    "        threading.Thread.__init__(self)\n",
    "        self.client_socket = client_socket\n",
    "        self.client_address = client_address\n",
    "        # Initialize ML model here\n",
    "        self.my_model = None  # Model will be initialized after getting the date from the client\n",
    "        \n",
    "    def run(self):\n",
    "        self.greet_user()  # Greet the user first\n",
    "        self.ask_for_current_date()  # Then ask for the current date\n",
    "        self.handle_conversation()  # Handle the rest of the conversation\n",
    "        self.goodbye_user()  # Say goodbye when the conversation ends\n",
    "\n",
    "    def greet_user(self):\n",
    "        self.send_message(\"Hello, I'm Oracle, your weather and bike hire prediction assistant. \"\n",
    "                          \"To provide accurate predictions, I need to know today's date. \"\n",
    "                          \"Please enter the date in YYYY-MM-DD format.\")\n",
    "        time.sleep(1)\n",
    "    \n",
    "    def ask_for_current_date(self):\n",
    "        while True:\n",
    "            date_str = self.receive_message().strip()\n",
    "            try:\n",
    "                current_date = pd.to_datetime(date_str)\n",
    "                self.my_model = MyModel(current_date)  # Initialize the ML model with the date\n",
    "                self.send_message(f\"Thank you. I have set the date to {current_date.strftime('%Y-%m-%d')}. \"\n",
    "                                  \"You can now ask me about the weather or bike hire numbers for the next 7 days. \"\n",
    "                                  \"For example, 'What's the weather like on day 3?' or 'Predict bike hires for day 5.'\")\n",
    "                break  # Exit the loop if the date is valid\n",
    "            except ValueError:\n",
    "                self.send_message(\"The date format is incorrect. Please enter the date in YYYY-MM-DD format.\")\n",
    "\n",
    "    def handle_conversation(self):\n",
    "        try:\n",
    "            while True:\n",
    "                user_input = self.receive_message().lower()\n",
    "    \n",
    "                day = self.extract_day(user_input)\n",
    "    \n",
    "                if \"weather\" in user_input:\n",
    "                    self.predict_weather(day)\n",
    "                elif \"bike hires\" in user_input:\n",
    "                    self.predict_bike_hires(day)\n",
    "                elif \"goodbye\" in user_input:\n",
    "                    break\n",
    "                else:\n",
    "                    self.send_message(\"I'm sorry, I didn't understand. Ask about weather or bike hires.\")\n",
    "        except Exception as e:\n",
    "            print(f\"Error in handle_conversation: {e}\")\n",
    "    \n",
    "    def extract_day(self, user_input):\n",
    "        # Use expressions to find day numbers in the message\n",
    "        match = re.search(r'\\bday\\s(\\d+)', user_input)\n",
    "        if match:\n",
    "            day = int(match.group(1))\n",
    "            if 1 <= day <= 7:\n",
    "                return day\n",
    "        return 1  # Default to Day 1 if no valid day is found\n",
    "\n",
    "    def goodbye_user(self):\n",
    "        self.send_message(\"Thank you for consulting the Oracle. Have a great day!\")\n",
    "        time.sleep(1)\n",
    "        self.client_socket.close()\n",
    "        print_lock.release()\n",
    "\n",
    "    def predict_weather(self, day):\n",
    "        date_str = self.day_to_date(day)\n",
    "        weather_features = ['tempmax', 'tempmin', 'windspeed', 'precip']\n",
    "        predictions = [self.my_model.predict(day, feature) for feature in weather_features]\n",
    "    \n",
    "        response = (f\"For {date_str}, the forecast is: \"\n",
    "                    f\"high of {predictions[0]:.1f}°C, low of {predictions[1]:.1f}°C, \"\n",
    "                    f\"wind speed at {predictions[2]:.1f} km/h, and precipitation levels around {predictions[3]:.1f} mm.\")\n",
    "        self.send_message(response)\n",
    "    \n",
    "    def predict_bike_hires(self, day):\n",
    "        date_str = self.day_to_date(day)\n",
    "        value = self.my_model.predict(day, 'Number of Bicycle Hires')\n",
    "    \n",
    "        response = f\"For {date_str}, the expected number of bike hires is approximately {value:.0f}.\"\n",
    "        self.send_message(response)\n",
    "\n",
    "    def send_message(self, message):\n",
    "        try:\n",
    "            print(\"Sending message:\", message)\n",
    "            self.client_socket.send(message.encode('utf-8'))\n",
    "        except Exception as e:\n",
    "            print(f\"Error in send_message: {e}\")\n",
    "\n",
    "    def receive_message(self):\n",
    "        try:\n",
    "            data = self.client_socket.recv(1024)\n",
    "            user_input = data.decode('utf-8')\n",
    "            print(\"Received message:\", user_input)\n",
    "            return user_input\n",
    "        except Exception as e:\n",
    "            print(f\"Error in receive_message: {e}\")\n",
    "            return \"\"\n",
    "\n",
    "    def day_to_date(self, day):\n",
    "            # Convert the day number to a date string\n",
    "            return f\"Day {day}\"\n",
    "\n",
    "def Main():\n",
    "    host = \"127.0.0.1\"\n",
    "    port = 12345\n",
    "\n",
    "    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)\n",
    "    s.bind((host, port))\n",
    "    print(\"Socket bound to port\", port)\n",
    "\n",
    "    s.listen(5)\n",
    "    print(\"Socket is listening\")\n",
    "\n",
    "    while True:\n",
    "        c, addr = s.accept()    # Establish connection with the client\n",
    "        print_lock.acquire()    # Lock acquired by the client\n",
    "        print(\"Connected to:\", addr[0], \":\", addr[1])\n",
    "\n",
    "        oracle_thread = OracleBotThread(c, addr)\n",
    "        oracle_thread.start()\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    Main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
